# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 'autopartes'

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  NODE_ENV: production
  REACT_APP_CANONICAL_ROOT_URL: https://autopartes.azurewebsites.net
  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
  REACT_APP_SHARETRIBE_MARKETPLACE_CURRENCY: USD
  REACT_APP_SHARETRIBE_SDK_CLIENT_ID: 89b08fc3-c97c-4d4c-8f14-60b12147a792
  REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_51J8G32EpYjJ2yJRRUCaYLperutnuOjcETJwY0SoKwbclitrvbwQZAodHJd8NlZP8L2iorAy18UBro2lkzzG3f1Xo00kfPcNunU
  SHARETRIBE_SDK_CLIENT_SECRET: ${{ secrets.SHARETRIBE_SDK_CLIENT_SECRET }}
  REACT_APP_AVAILABILITY_ENABLED: true
  REACT_APP_DEFAULT_SEARCHES_ENABLED: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          yarn install
          yarn build
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      
      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'autopartes'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_98137159A4174E768BCB3BFC8EF20B74 }}
          package: .